spring:
  application:
    name: config-server
server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flyer21/SpringcloudConfig.git
          searchPaths: respo
      label: master
      server:
        git:
          username: flyer21
          password: frf12345
