server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/flyer21/military
          searchPaths: SpringcloudConfig
          username: flyer21@163.net
          password: frf12345
