spring:
  application:
    name: oauth-server
server:
  port: 8000
  contextPath: /uaa

security:
  user:
    password: password
  ignored: /dist/**,/css/**,/js/**,/favicon.ico,/w111ebjars/**
logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/