server.contextPath: /uaa
security.user.password: password
security.ignored: /css/**,/js/**,/favicon.ico,/webjars/**
logging.level.org.springframework.security: DEBUG
spring:
  application:
    name: oauth-server
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/